// <auto-generated />
using System;
using HotelManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelManager.Models.BAN_NHA_HANG", b =>
                {
                    b.Property<string>("MaBan")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenBan")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaBan");

                    b.ToTable("BAN_NHA_HANG");
                });

            modelBuilder.Entity("HotelManager.Models.CHI_TIET_DAT_PHONG", b =>
                {
                    b.Property<string>("MaChiTietDatPhong")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DAT_PHONGMaDatPhong")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PHONGMaPhong")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("SoNgayO")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietDatPhong");

                    b.ToTable("CHI_TIET_DAT_PHONG");
                });

            modelBuilder.Entity("HotelManager.Models.CHI_TIET_DICH_VU", b =>
                {
                    b.Property<string>("MaChiTietDichVu")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DICH_VUMaDichVu")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KHACH_HANGMaKH")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KHO_VAT_TUMaVatTu")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PHONGMaPhong")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ThoiGianSuDung")
                        .HasColumnType("datetime2");

                    b.HasKey("MaChiTietDichVu");

                    b.ToTable("CHI_TIET_DICH_VU");
                });

            modelBuilder.Entity("HotelManager.Models.CHUC_VU", b =>
                {
                    b.Property<string>("MaChucVu")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PHONG_BANMaPB")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenChucVu")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChucVu");

                    b.ToTable("CHUC_VU");
                });

            modelBuilder.Entity("HotelManager.Models.DAT_PHONG", b =>
                {
                    b.Property<string>("MaDatPhong")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DOI_TACMaDoiTac")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KHACH_HANGMaKH")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KenhDatPhong")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoLuongKhach")
                        .HasColumnType("int");

                    b.Property<decimal?>("TienCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiDatPhong")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDatPhong");

                    b.ToTable("DAT_PHONG");
                });

            modelBuilder.Entity("HotelManager.Models.DICH_VU", b =>
                {
                    b.Property<string>("MaDichVu")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("DonViTinh")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoaiDichVu")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDichVu")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDichVu");

                    b.ToTable("DICH_VU");
                });

            modelBuilder.Entity("HotelManager.Models.DOI_TAC", b =>
                {
                    b.Property<string>("MaDoiTac")
                        .HasColumnType("varchar(20)");

                    b.Property<double?>("ChietKhau")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("HanMucCongNo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiDoiTac")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NguoiLienHe")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SDT")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("SoDuCongNo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenDoiTac")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDoiTac");

                    b.ToTable("DOI_TAC");
                });

            modelBuilder.Entity("HotelManager.Models.HOA_DON", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DAT_PHONGMaDatPhong")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KHACH_HANGMaKH")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NHAN_VIENMaNV")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TienCocDaTru")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienDichVu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienGiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienNhaHang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienPhong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienThueVAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongTienThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHoaDon");

                    b.ToTable("HOA_DON");
                });

            modelBuilder.Entity("HotelManager.Models.HOA_DON_NHA_HANG", b =>
                {
                    b.Property<string>("MaHoaDonNhaHang")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BAN_NHA_HANGMaBan")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DAT_PHONGMaDatPhong")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhThucThanhToan")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NHAN_VIENMaNV")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TongTienMonAn")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHoaDonNhaHang");

                    b.ToTable("HOA_DON_NHA_HANG");
                });

            modelBuilder.Entity("HotelManager.Models.KHACH_HANG", b =>
                {
                    b.Property<string>("MaKH")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Blacklist")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("DiemThuong")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GhiChuDacBiet")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HangThanhVien")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SDT")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SoCCCD")
                        .HasColumnType("varchar(12)");

                    b.HasKey("MaKH");

                    b.ToTable("KHACH_HANG");
                });

            modelBuilder.Entity("HotelManager.Models.KHO_VAT_TU", b =>
                {
                    b.Property<string>("MaVatTu")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("DonGiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoaiVatTu")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTonToiThieu")
                        .HasColumnType("int");

                    b.Property<string>("TenVatTu")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaVatTu");

                    b.ToTable("KHO_VAT_TU");
                });

            modelBuilder.Entity("HotelManager.Models.LICH_LAM_VIEC", b =>
                {
                    b.Property<string>("MaLich")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CaLamViec")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("GioCheckIn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("GioCheckOut")
                        .HasColumnType("datetime");

                    b.Property<string>("NHAN_VIENMaNV")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NgayLamViec")
                        .HasColumnType("date");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLich");

                    b.ToTable("LICH_LAM_VIEC");
                });

            modelBuilder.Entity("HotelManager.Models.NHAN_VIEN", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CHUC_VUMaChucVu")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayVaoLam")
                        .HasColumnType("date");

                    b.Property<string>("SDT")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SoCCCD")
                        .HasColumnType("varchar(12)");

                    b.HasKey("MaNV");

                    b.ToTable("NHAN_VIEN");
                });

            modelBuilder.Entity("HotelManager.Models.PHIEU_BAO_CAO_SU_CO", b =>
                {
                    b.Property<string>("MaPhieuBaoCao")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("HinhAnhDinhKem")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("KHO_VAT_TUMaVatTu")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MoTaSuCo")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MucDoUuTien")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NHAN_VIENMaNV")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhieuBaoCao");

                    b.ToTable("PHIEU_BAO_CAO_SU_CO");
                });

            modelBuilder.Entity("HotelManager.Models.PHIEU_LUU_TRU", b =>
                {
                    b.Property<string>("MaPhieuLuuTru")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KHACH_HANGMaKH")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NHAN_VIENMaNV")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PHONGMaPhong")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ThoiGianCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiLuuTru")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhieuLuuTru");

                    b.ToTable("PHIEU_LUU_TRU");
                });

            modelBuilder.Entity("HotelManager.Models.PHONG", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("GiaTheoGio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaTheoNgay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiPhong")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SoGiuong")
                        .HasColumnType("int");

                    b.Property<string>("SoPhong")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("SucChuaToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TRANG_THAI_PHONGMaTrangThai")
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaPhong");

                    b.ToTable("PHONG");
                });

            modelBuilder.Entity("HotelManager.Models.PHONG_BAN", b =>
                {
                    b.Property<string>("MaPB")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenPB")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPB");

                    b.ToTable("PHONG_BAN");
                });

            modelBuilder.Entity("HotelManager.Models.TAI_KHOAN", b =>
                {
                    b.Property<string>("MaTaiKhoan")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VaiTro")
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TAI_KHOAN");
                });

            modelBuilder.Entity("HotelManager.Models.THANH_TOAN", b =>
                {
                    b.Property<string>("MaThanhToan")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("HOA_DONMaHoaDon")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("HOA_DON_NHA_HANGMaHoaDonNhaHang")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaGiaoDichNgoai")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ThoiGianGiaoDich")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiGiaoDich")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaThanhToan");

                    b.ToTable("THANH_TOAN");
                });

            modelBuilder.Entity("HotelManager.Models.TRANG_THAI_PHONG", b =>
                {
                    b.Property<string>("MaTrangThai")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TrangThaiPhong")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThaiVeSinh")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTrangThai");

                    b.ToTable("TRANG_THAI_PHONG");
                });
#pragma warning restore 612, 618
        }
    }
}
